from BaseClasses import ItemClassification

from .constants import *

core_rooms = {
    "Antechamber": {
        ROOM_ITEM_ID_KEY: 45,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_X,
    },
    "Room 46": {
        ROOM_ITEM_ID_KEY: 46,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Entrance Hall": {
        ROOM_ITEM_ID_KEY: 2,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_X,
    },
}

classrooms = {
    "Classroom 1": {
        ROOM_ITEM_ID_KEY: 101,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Classroom 2": {
        ROOM_ITEM_ID_KEY: 102,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Classroom 3": {
        ROOM_ITEM_ID_KEY: 103,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Classroom 4": {
        ROOM_ITEM_ID_KEY: 104,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Classroom 5": {
        ROOM_ITEM_ID_KEY: 105,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Classroom 6": {
        ROOM_ITEM_ID_KEY: 106,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Classroom 7": {
        ROOM_ITEM_ID_KEY: 107,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Classroom 8": {
        ROOM_ITEM_ID_KEY: 108,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Classroom Exam": {
        ROOM_ITEM_ID_KEY: 109,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
}

secret_blue = {
    "Dovecote": {
        ROOM_ITEM_ID_KEY: 201,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "The Kennel": {
        ROOM_ITEM_ID_KEY: 202,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
    },
    "Clock Tower": {
        ROOM_ITEM_ID_KEY: 203,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Planetarium": {
        ROOM_ITEM_ID_KEY: 204,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Mechanarium": {
        ROOM_ITEM_ID_KEY: 205,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,  # This is the most restrictive state of the mechanarium.
    },
    "Toolshed": {
        ROOM_ITEM_ID_KEY: 206,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Shelter": {
        ROOM_ITEM_ID_KEY: 207,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Schoolhouse": {
        ROOM_ITEM_ID_KEY: 208,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Shrine": {
        ROOM_ITEM_ID_KEY: 209,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
} | classrooms


blue_001_012 = {
    "The Foundation": {
        ROOM_ITEM_ID_KEY: 1,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
    },
    "Spare Room": {
        ROOM_ITEM_ID_KEY: 3,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
    },
    "Rotunda": {
        ROOM_ITEM_ID_KEY: 4,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_X,
    },
    "Parlor": {
        ROOM_ITEM_ID_KEY: 5,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Billiard Room": {
        ROOM_ITEM_ID_KEY: 6,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Gallery": {
        ROOM_ITEM_ID_KEY: 7,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
    },
    "Room 8": {
        ROOM_ITEM_ID_KEY: 8,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Closet": {
        ROOM_ITEM_ID_KEY: 9,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Walk-In Closet": {
        ROOM_ITEM_ID_KEY: 10,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Attic": {
        ROOM_ITEM_ID_KEY: 11,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Storeroom": {
        ROOM_ITEM_ID_KEY: 12,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
}
blue_013_024 = {
    "Nook": {
        ROOM_ITEM_ID_KEY: 13,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Garage": {
        ROOM_ITEM_ID_KEY: 14,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Music Room": {
        ROOM_ITEM_ID_KEY: 15,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Locker Room": {
        ROOM_ITEM_ID_KEY: 16,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
    },
    "Den": {
        ROOM_ITEM_ID_KEY: 17,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
    },
    "Wine Cellar": {
        ROOM_ITEM_ID_KEY: 18,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Troophy Room": {
        ROOM_ITEM_ID_KEY: 19,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Ballroom": {
        ROOM_ITEM_ID_KEY: 20,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
    },
    "Pantry": {
        ROOM_ITEM_ID_KEY: 21,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Rumpus Room": {
        ROOM_ITEM_ID_KEY: 22,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
    },
    "Vault": {
        ROOM_ITEM_ID_KEY: 23,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Office": {
        ROOM_ITEM_ID_KEY: 24,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
}
blue_025_036 = {
    "Drawing Room": {
        ROOM_ITEM_ID_KEY: 25,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
    },
    "Study": {
        ROOM_ITEM_ID_KEY: 26,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Library": {
        ROOM_ITEM_ID_KEY: 27,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Chamber of Mirrors": {
        ROOM_ITEM_ID_KEY: 28,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "The Pool": {
        ROOM_ITEM_ID_KEY: 29,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
    },
    "Drafting Studio": {
        ROOM_ITEM_ID_KEY: 30,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
    },
    "Utility Closet": {
        ROOM_ITEM_ID_KEY: 31,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Boiler Room": {
        ROOM_ITEM_ID_KEY: 32,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
    },
    "Pump Room": {
        ROOM_ITEM_ID_KEY: 33,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Security": {
        ROOM_ITEM_ID_KEY: 34,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
    },
    "Workshop": {
        ROOM_ITEM_ID_KEY: 35,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
    },
    "Laboratory": {
        ROOM_ITEM_ID_KEY: 36,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
}
blue_037_046 = {
    "Sauna": {
        ROOM_ITEM_ID_KEY: 37,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Coat Check": {
        ROOM_ITEM_ID_KEY: 38,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Mail Room": {
        ROOM_ITEM_ID_KEY: 39,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Freezer": {
        ROOM_ITEM_ID_KEY: 40,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Dining Room": {
        ROOM_ITEM_ID_KEY: 41,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
    },
    "Observatory": {
        ROOM_ITEM_ID_KEY: 42,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Conference Room": {
        ROOM_ITEM_ID_KEY: 43,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
    },
    "Aquarium": {
        ROOM_ITEM_ID_KEY: 44,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
    },
}

blue_rooms = (
    core_rooms | secret_blue | blue_001_012 | blue_013_024 | blue_025_036 | blue_037_046
)

bedrooms = {
    "Dormitory": {
        ROOM_ITEM_ID_KEY: 301,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Hovel": {
        ROOM_ITEM_ID_KEY: 302,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Bedroom": {
        ROOM_ITEM_ID_KEY: 303,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Boudoir": {
        ROOM_ITEM_ID_KEY: 304,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Guest Befroom": {
        ROOM_ITEM_ID_KEY: 305,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Nursery": {
        ROOM_ITEM_ID_KEY: 306,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Servants Quarters": {
        ROOM_ITEM_ID_KEY: 307,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Bunk Room": {
        ROOM_ITEM_ID_KEY: 308,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Her Ladyships Chambers": {
        ROOM_ITEM_ID_KEY: 309,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Master Bedroom": {
        ROOM_ITEM_ID_KEY: 310,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
}

hallways = {
    "Vestibule": {
        ROOM_ITEM_ID_KEY: 401,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_X,
    },
    "Tunnel": {
        ROOM_ITEM_ID_KEY: 402,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
    },
    "Hallway": {
        ROOM_ITEM_ID_KEY: 403,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
    },
    "West Wing Hall": {
        ROOM_ITEM_ID_KEY: 404,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
    },
    "East Wing Hall": {
        ROOM_ITEM_ID_KEY: 405,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
    },
    "Corridor": {
        ROOM_ITEM_ID_KEY: 406,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
    },
    "Passageway": {
        ROOM_ITEM_ID_KEY: 407,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_X,
    },
    "Secret Passage": {
        ROOM_ITEM_ID_KEY: 408,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
    },
    "Foyer": {
        ROOM_ITEM_ID_KEY: 409,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
    },
    "Great Hall": {
        ROOM_ITEM_ID_KEY: 410,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_X,
    },
}

green_rooms = {
    "Solarium": {
        ROOM_ITEM_ID_KEY: 501,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Conservatory": {
        ROOM_ITEM_ID_KEY: 502,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Root Cellar": {
        ROOM_ITEM_ID_KEY: 503,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Terrace": {
        ROOM_ITEM_ID_KEY: 504,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Patio": {
        ROOM_ITEM_ID_KEY: 505,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Courtyard": {
        ROOM_ITEM_ID_KEY: 506,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
    },
    "Cloister": {
        ROOM_ITEM_ID_KEY: 507,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_X,
    },
    "Veranda": {
        ROOM_ITEM_ID_KEY: 508,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
    },
    "Greenhouse": {
        ROOM_ITEM_ID_KEY: 509,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Morning Room": {
        ROOM_ITEM_ID_KEY: 510,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Secret Garden": {
        ROOM_ITEM_ID_KEY: 511,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
    },
}

shops = {
    "Casino": {
        ROOM_ITEM_ID_KEY: 601,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Trading Post": {
        ROOM_ITEM_ID_KEY: 602,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Commissary": {
        ROOM_ITEM_ID_KEY: 603,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Kitchen": {
        ROOM_ITEM_ID_KEY: 604,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Locksmith": {
        ROOM_ITEM_ID_KEY: 605,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Showroom": {
        ROOM_ITEM_ID_KEY: 606,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
    },
    "Laundry Room": {
        ROOM_ITEM_ID_KEY: 607,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Bookshop": {
        ROOM_ITEM_ID_KEY: 608,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "The Armory": {
        ROOM_ITEM_ID_KEY: 609,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Mount Holly Gift Shop": {
        ROOM_ITEM_ID_KEY: 610,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
    },
}
red_rooms = {
    "Lost And Found": {
        ROOM_ITEM_ID_KEY: 701,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Closed Exhibit": {
        ROOM_ITEM_ID_KEY: 702,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
    },
    "Lavatory": {
        ROOM_ITEM_ID_KEY: 703,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
    "Chapel": {
        ROOM_ITEM_ID_KEY: 704,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
    },
    "Maids Chamber": {
        ROOM_ITEM_ID_KEY: 705,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Archives": {
        ROOM_ITEM_ID_KEY: 706,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_X,
    },
    "Gymnasium": {
        ROOM_ITEM_ID_KEY: 707,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
    },
    "Darkroom": {
        ROOM_ITEM_ID_KEY: 708,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
    },
    "Weight Room": {
        ROOM_ITEM_ID_KEY: 709,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_X,
    },
    "Furnace": {
        ROOM_ITEM_ID_KEY: 710,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
}
black_rooms = {
    "Treasure Trove": {
        ROOM_ITEM_ID_KEY: 801,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
    },
    "Throne Room": {
        ROOM_ITEM_ID_KEY: 802,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
    },
    "Tomb": {
        ROOM_ITEM_ID_KEY: 803,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT: 0,
        ROOM_CHEST_SPOT_COUNT: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
    },
}

rooms = blue_rooms | bedrooms | hallways | green_rooms | shops | red_rooms | black_rooms
